// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubscription(ctx context.Context, db DBTX, arg CreateSubscriptionParams) (Subscriptions, error)
	DeleteSubscription(ctx context.Context, db DBTX, id uuid.UUID) (int64, error)
	ListSubscriptions(ctx context.Context, db DBTX, arg ListSubscriptionsParams) ([]Subscriptions, error)
	ReadSubscription(ctx context.Context, db DBTX, id uuid.UUID) (Subscriptions, error)
	TotalSubscriptionsCost(ctx context.Context, db DBTX, arg TotalSubscriptionsCostParams) (int64, error)
	UpdateSubscription(ctx context.Context, db DBTX, arg UpdateSubscriptionParams) (Subscriptions, error)
}

var _ Querier = (*Queries)(nil)
