// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
insert into subscriptions (
    service_name, price, user_id, start_date, end_date
) values (
    $1, $2, $3, $4, $5
)
returning id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string
	Price       int32
	UserID      uuid.UUID
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) CreateSubscription(ctx context.Context, db DBTX, arg CreateSubscriptionParams) (Subscriptions, error) {
	row := db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :one
with deleted_rows as (
    delete from subscriptions
    where id = $1
    returning id, service_name, price, user_id, start_date, end_date, created_at, updated_at
)
select count(*) from deleted_rows
`

func (q *Queries) DeleteSubscription(ctx context.Context, db DBTX, id uuid.UUID) (int64, error) {
	row := db.QueryRow(ctx, deleteSubscription, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
select id, service_name, price, user_id, start_date, end_date, created_at, updated_at
from subscriptions
where ($1::uuid is null or user_id = $1::uuid)
    and ($2::int is null or price = $2::int)
    and ($3::text is null or service_name = $3::text)
    and ($4::date is null or start_date = $4::date)
    and ($5::date is null or end_date = $5::date)
`

type ListSubscriptionsParams struct {
	UserID      pgtype.UUID
	Price       pgtype.Int4
	ServiceName pgtype.Text
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) ListSubscriptions(ctx context.Context, db DBTX, arg ListSubscriptionsParams) ([]Subscriptions, error) {
	rows, err := db.Query(ctx, listSubscriptions,
		arg.UserID,
		arg.Price,
		arg.ServiceName,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriptions
	for rows.Next() {
		var i Subscriptions
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSubscription = `-- name: ReadSubscription :one
select id, service_name, price, user_id, start_date, end_date, created_at, updated_at
from subscriptions
where id = $1
`

func (q *Queries) ReadSubscription(ctx context.Context, db DBTX, id uuid.UUID) (Subscriptions, error) {
	row := db.QueryRow(ctx, readSubscription, id)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const totalSubscriptionsCost = `-- name: TotalSubscriptionsCost :one
select coalesce(sum(
    (
        (
            extract(year from overlap_end) * 12 + extract(month from overlap_end)
        ) -
        (
            extract(year from overlap_start) * 12 + extract(month from overlap_start)
        ) + 1
    ) * price
), 0)::bigint AS cost
from (
    select
        price,
        greatest(start_date, $1::date) as overlap_start,
        least(coalesce(end_date, $2::date), $2::date) as overlap_end
    from subscriptions
    where
        start_date <= $2::date
        and (end_date is null or end_date >= $1::date)
        and ($3::uuid is null or user_id = $3::uuid)
        and ($4::text is null or service_name = $4::text)
) t
`

type TotalSubscriptionsCostParams struct {
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	UserID      pgtype.UUID
	ServiceName pgtype.Text
}

func (q *Queries) TotalSubscriptionsCost(ctx context.Context, db DBTX, arg TotalSubscriptionsCostParams) (int64, error) {
	row := db.QueryRow(ctx, totalSubscriptionsCost,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
		arg.ServiceName,
	)
	var cost int64
	err := row.Scan(&cost)
	return cost, err
}

const updateSubscription = `-- name: UpdateSubscription :one
update subscriptions
set service_name = $2,
    price = $3,
    user_id = $4,
    start_date = $5,
    end_date = $6
where id = $1
returning id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID          uuid.UUID
	ServiceName string
	Price       int32
	UserID      uuid.UUID
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) UpdateSubscription(ctx context.Context, db DBTX, arg UpdateSubscriptionParams) (Subscriptions, error) {
	row := db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
